/* Generated by scripts/open_fighter_pipeline/build_atlases.mjs. */
export const OPEN_ANIMATION_METADATA = {
  "kaykit-knight": {
    "idle": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_A",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Crouching",
      "coverage": "direct"
    },
    "walk": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walking_A",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walking_Backwards",
      "coverage": "adapted"
    },
    "dash": {
      "frameCount": 12,
      "fps": 19,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Running_A",
      "coverage": "direct"
    },
    "run": {
      "frameCount": 12,
      "fps": 19,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Running_A",
      "coverage": "direct"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 25,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Start",
      "coverage": "direct"
    },
    "jump": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Full_Short",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Full_Long",
      "coverage": "direct"
    },
    "fall": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Idle",
      "coverage": "direct"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Idle",
      "coverage": "adapted"
    },
    "jab": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Stab",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Slice_Horizontal",
      "coverage": "direct"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Slice_Horizontal",
      "coverage": "direct"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Chop",
      "coverage": "direct"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 15,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Slice_Diagonal",
      "coverage": "direct"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Attack_Slice",
      "coverage": "direct"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Attack_Chop",
      "coverage": "direct"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Attack_Spin",
      "coverage": "direct"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Attack_Spinning",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Jump_Chop",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Unarmed_Attack_Kick",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_1H_Attack_Chop",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Attack_Chop",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Ranged_Magic_Shoot",
      "coverage": "adapted"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Ranged_Magic_Spellcasting_Long",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Full_Long",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Block_Attack",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dodge_Left",
      "coverage": "direct"
    },
    "roll_forward": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dodge_Forward",
      "coverage": "direct"
    },
    "roll_back": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dodge_Backward",
      "coverage": "direct"
    },
    "air_dodge": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dodge_Right",
      "coverage": "adapted"
    },
    "shield": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Blocking",
      "coverage": "direct"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_2H_Idle",
      "coverage": "adapted"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "PickUp",
      "coverage": "direct"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Use_Item",
      "coverage": "direct"
    },
    "grab": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Interact",
      "coverage": "adapted"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Blocking",
      "coverage": "adapted"
    },
    "grabbed": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_A",
      "coverage": "adapted"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Throw",
      "coverage": "adapted"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Throw",
      "coverage": "adapted"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Throw",
      "coverage": "adapted"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Throw",
      "coverage": "adapted"
    },
    "hurt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_A",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 12,
      "fps": 17,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_B",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Lie_Idle",
      "coverage": "direct"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Crawling",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Spawn_Ground",
      "coverage": "direct"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Waving",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Cheering",
      "coverage": "direct"
    }
  },
  "george": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "walk": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk_Tall",
      "coverage": "author_required"
    },
    "dash": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run",
      "coverage": "direct"
    },
    "run": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run",
      "coverage": "direct"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jump": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fall": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "direct"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "SwordSlash",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 24,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Shoot",
      "coverage": "adapted"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Tall",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "SwordSlash",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 12,
      "fps": 26,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve_1",
      "coverage": "author_required"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run",
      "coverage": "author_required"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Tall",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Holding",
      "coverage": "adapted"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Pickup",
      "coverage": "direct"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "SwordSlash",
      "coverage": "adapted"
    },
    "grab": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Pickup",
      "coverage": "author_required"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Pickup",
      "coverage": "author_required"
    },
    "grabbed": {
      "frameCount": 12,
      "fps": 26,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve_1",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "author_required"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Kick",
      "coverage": "author_required"
    },
    "hurt": {
      "frameCount": 12,
      "fps": 26,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve_1",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 12,
      "fps": 26,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve_2",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Pickup",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hello",
      "coverage": "adapted"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hello",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 15,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dance",
      "coverage": "direct"
    }
  },
  "platformer": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Gun",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Duck",
      "coverage": "direct"
    },
    "walk": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk_Gun",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "dash": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Gun",
      "coverage": "direct"
    },
    "run": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Gun",
      "coverage": "direct"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jump": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fall": {
      "frameCount": 12,
      "fps": 24,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Idle",
      "coverage": "direct"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 24,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Idle",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Shoot",
      "coverage": "adapted"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Shoot",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Shoot",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Shoot",
      "coverage": "direct"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run_Shoot",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Duck",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitReact",
      "coverage": "author_required"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run",
      "coverage": "author_required"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Run",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Duck",
      "coverage": "author_required"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Gun",
      "coverage": "adapted"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Duck",
      "coverage": "author_required"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Shoot",
      "coverage": "adapted"
    },
    "grab": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "grabbed": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitReact",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 14,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch",
      "coverage": "author_required"
    },
    "hurt": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitReact",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 12,
      "fps": 20,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitReact",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Land",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Wave",
      "coverage": "adapted"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Wave",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Yes",
      "coverage": "direct"
    }
  },
  "wolf": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2_HeadLow",
      "coverage": "direct"
    },
    "walk": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2",
      "coverage": "author_required"
    },
    "dash": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop",
      "coverage": "direct"
    },
    "run": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop",
      "coverage": "direct"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop_Jump",
      "coverage": "author_required"
    },
    "jump": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop_Jump",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop_Jump",
      "coverage": "author_required"
    },
    "fall": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_ToIdle",
      "coverage": "adapted"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_ToIdle",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop_Jump",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_HitReact_Left",
      "coverage": "author_required"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop",
      "coverage": "author_required"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 21,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 13,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Gallop_Jump",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2_HeadLow",
      "coverage": "author_required"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Eating",
      "coverage": "author_required"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "grab": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Eating",
      "coverage": "author_required"
    },
    "grabbed": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_HitReact_Left",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Attack",
      "coverage": "author_required"
    },
    "hurt": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_HitReact_Left",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_HitReact_Right",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_ToIdle",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2",
      "coverage": "author_required"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2",
      "coverage": "author_required"
    },
    "victory": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_2",
      "coverage": "author_required"
    }
  },
  "cactus": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "walk": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "No",
      "coverage": "author_required"
    },
    "dash": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "run": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jump": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fall": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "direct"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "author_required"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "grab": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "grabbed": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "hurt": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Yes",
      "coverage": "adapted"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "No",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dance",
      "coverage": "direct"
    }
  },
  "yeti": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "walk": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "No",
      "coverage": "author_required"
    },
    "dash": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "run": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jump": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fall": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "direct"
    },
    "forward_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "up_air": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "adapted"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "adapted"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "adapted"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "adapted"
    },
    "spot_dodge": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "author_required"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle",
      "coverage": "author_required"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "grab": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_InPlace",
      "coverage": "author_required"
    },
    "grabbed": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Bite_Front",
      "coverage": "author_required"
    },
    "hurt": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 10,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "HitRecieve",
      "coverage": "adapted"
    },
    "downed": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump",
      "coverage": "author_required"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Yes",
      "coverage": "adapted"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "No",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dance",
      "coverage": "direct"
    }
  },
  "quaternius-hero": {
    "idle": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Loop",
      "coverage": "direct"
    },
    "crouch": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Crouch_Idle_Loop",
      "coverage": "direct"
    },
    "walk": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk_Loop",
      "coverage": "direct"
    },
    "turn": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Walk_Formal_Loop",
      "coverage": "adapted"
    },
    "dash": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sprint_Loop",
      "coverage": "direct"
    },
    "run": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jog_Fwd_Loop",
      "coverage": "direct"
    },
    "jump_squat": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Start",
      "coverage": "direct"
    },
    "jump": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Loop",
      "coverage": "direct"
    },
    "double_jump": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "NinjaJump_Start",
      "coverage": "direct"
    },
    "fall": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "NinjaJump_Idle_Loop",
      "coverage": "direct"
    },
    "fast_fall": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "NinjaJump_Idle_Loop",
      "coverage": "author_required"
    },
    "jab": {
      "frameCount": 12,
      "fps": 17,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch_Jab",
      "coverage": "direct"
    },
    "dash_attack": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Dash",
      "coverage": "direct"
    },
    "forward_tilt": {
      "frameCount": 11,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_A",
      "coverage": "direct"
    },
    "up_tilt": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Hook",
      "coverage": "adapted"
    },
    "down_tilt": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_B",
      "coverage": "adapted"
    },
    "forward_smash": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Heavy_Combo",
      "coverage": "adapted"
    },
    "up_smash": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_C",
      "coverage": "adapted"
    },
    "down_smash": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_Combo",
      "coverage": "adapted"
    },
    "neutral_air": {
      "frameCount": 12,
      "fps": 15,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Punch_Cross",
      "coverage": "author_required"
    },
    "forward_air": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Attack",
      "coverage": "author_required"
    },
    "back_air": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Melee_Hook",
      "coverage": "author_required"
    },
    "up_air": {
      "frameCount": 11,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_A",
      "coverage": "author_required"
    },
    "down_air": {
      "frameCount": 12,
      "fps": 28,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Regular_B",
      "coverage": "author_required"
    },
    "neutral_special": {
      "frameCount": 12,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Spell_Simple_Shoot",
      "coverage": "direct"
    },
    "side_special": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Dash",
      "coverage": "direct"
    },
    "up_special": {
      "frameCount": 12,
      "fps": 16,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "NinjaJump_Start",
      "coverage": "author_required"
    },
    "down_special": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Block",
      "coverage": "direct"
    },
    "spot_dodge": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Roll",
      "coverage": "direct"
    },
    "roll_forward": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Roll",
      "coverage": "direct"
    },
    "roll_back": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Roll",
      "coverage": "author_required"
    },
    "air_dodge": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "NinjaJump_Idle_Loop",
      "coverage": "author_required"
    },
    "shield": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_Shield_Loop",
      "coverage": "direct"
    },
    "item_hold": {
      "frameCount": 12,
      "fps": 9,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Idle",
      "coverage": "direct"
    },
    "item_pickup": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "PickUp_Table",
      "coverage": "direct"
    },
    "item_attack": {
      "frameCount": 12,
      "fps": 10,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Sword_Attack",
      "coverage": "adapted"
    },
    "grab": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Interact",
      "coverage": "adapted"
    },
    "grab_hold": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Push_Loop",
      "coverage": "adapted"
    },
    "grabbed": {
      "frameCount": 9,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_Chest",
      "coverage": "author_required"
    },
    "forward_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "OverhandThrow",
      "coverage": "adapted"
    },
    "back_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "OverhandThrow",
      "coverage": "adapted"
    },
    "up_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "OverhandThrow",
      "coverage": "adapted"
    },
    "down_throw": {
      "frameCount": 12,
      "fps": 11,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "OverhandThrow",
      "coverage": "adapted"
    },
    "hurt": {
      "frameCount": 9,
      "fps": 30,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_Chest",
      "coverage": "direct"
    },
    "knockback": {
      "frameCount": 12,
      "fps": 18,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Hit_Knockback",
      "coverage": "direct"
    },
    "downed": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Death01",
      "coverage": "adapted"
    },
    "ledge": {
      "frameCount": 12,
      "fps": 22,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "ClimbUp_1m",
      "coverage": "direct"
    },
    "entrance": {
      "frameCount": 12,
      "fps": 12,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Jump_Land",
      "coverage": "adapted"
    },
    "taunt": {
      "frameCount": 12,
      "fps": 8,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Idle_No_Loop",
      "coverage": "direct"
    },
    "victory": {
      "frameCount": 12,
      "fps": 15,
      "columns": 8,
      "cellSize": 192,
      "sourceAction": "Dance_Loop",
      "coverage": "direct"
    }
  }
} as const;
